// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"dx/internal/adapters/container_image_repository"
	"dx/internal/adapters/container_orchestrator"
	"dx/internal/adapters/filesystem"
	"dx/internal/adapters/keyring"
	"dx/internal/adapters/scm"
	"dx/internal/adapters/symmetric_encryptor"
	"dx/internal/adapters/templater"
	"dx/internal/core"
	"dx/internal/core/handler"
	"dx/internal/ports"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InjectConfigRepo() (core.ConfigRepository, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	return fileSystemConfigRepository, nil
}

func InjectSecretRepository() (core.SecretsRepository, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	return secretsRepository, nil
}

func InjectBuildCommandHandler() (handler.BuildCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	gitClient := scm.ProvideGitClient()
	git := scm.ProvideGit(gitClient)
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater)
	buildCommandHandler := handler.ProvideBuildCommandHandler(fileSystemConfigRepository, git, dockerRepository)
	return buildCommandHandler, nil
}

func InjectInstallCommandHandler() (handler.InstallCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater)
	kubernetes, err := container_orchestrator.ProvideKubernetes(fileSystemConfigRepository, secretsRepository, portsTemplater)
	if err != nil {
		return handler.InstallCommandHandler{}, err
	}
	devProxyManager := core.ProvideDevProxyManager(fileSystemConfigRepository, osFileSystem, dockerRepository, kubernetes)
	environmentEnsurer := core.ProvideEnvironmentEnsurer(fileSystemConfigRepository, kubernetes)
	gitClient := scm.ProvideGitClient()
	git := scm.ProvideGit(gitClient)
	installCommandHandler := handler.ProvideInstallCommandHandler(fileSystemConfigRepository, dockerRepository, kubernetes, devProxyManager, environmentEnsurer, git)
	return installCommandHandler, nil
}

func InjectUninstallCommandHandler() (handler.UninstallCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	kubernetes, err := container_orchestrator.ProvideKubernetes(fileSystemConfigRepository, secretsRepository, portsTemplater)
	if err != nil {
		return handler.UninstallCommandHandler{}, err
	}
	environmentEnsurer := core.ProvideEnvironmentEnsurer(fileSystemConfigRepository, kubernetes)
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater)
	devProxyManager := core.ProvideDevProxyManager(fileSystemConfigRepository, osFileSystem, dockerRepository, kubernetes)
	uninstallCommandHandler := handler.ProvideUninstallCommandHandler(fileSystemConfigRepository, kubernetes, environmentEnsurer, devProxyManager)
	return uninstallCommandHandler, nil
}

func InjectGenEnvKeyCommandHandler() (handler.GenEnvKeyCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	kubernetes, err := container_orchestrator.ProvideKubernetes(fileSystemConfigRepository, secretsRepository, portsTemplater)
	if err != nil {
		return handler.GenEnvKeyCommandHandler{}, err
	}
	genEnvKeyCommandHandler := handler.ProvideGenEnvKeyCommandHandler(fileSystemConfigRepository, osFileSystem, kubernetes)
	return genEnvKeyCommandHandler, nil
}

func InjectContextCommandHandler() (handler.ContextCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	gitClient := scm.ProvideGitClient()
	git := scm.ProvideGit(gitClient)
	dockerRepository := container_image_repository.ProvideDockerRepository(fileSystemConfigRepository, secretsRepository, portsTemplater)
	contextCommandHandler := handler.ProvideContextCommandHandler(fileSystemConfigRepository, git, dockerRepository)
	return contextCommandHandler, nil
}

func InjectInitializeCommandHandler() (handler.InitializeCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	initializeCommandHandler := handler.ProvideInitializeCommandHandler(fileSystemConfigRepository)
	return initializeCommandHandler, nil
}

func InjectSecretCommandHandler() (handler.SecretCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	secretCommandHandler := handler.ProvideSecretCommandHandler(secretsRepository, fileSystemConfigRepository)
	return secretCommandHandler, nil
}

func InjectRunCommandHandler() (handler.RunCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	gitClient := scm.ProvideGitClient()
	git := scm.ProvideGit(gitClient)
	runCommandHandler := handler.ProvideRunCommandHandler(fileSystemConfigRepository, secretsRepository, portsTemplater, git)
	return runCommandHandler, nil
}

func InjectShowVarsCommandHandler() (handler.ShowVarsCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	showVarsCommandHandler := handler.ProvideShowVarsCommandHandler(secretsRepository, fileSystemConfigRepository)
	return showVarsCommandHandler, nil
}

func InjectGenerateCommandHandler() (handler.GenerateCommandHandler, error) {
	osFileSystem := filesystem.ProvideOsFileSystem()
	portsKeyring := keyring.ProvideZalandoKeyring()
	aesGcmEncryptor := symmetric_encryptor.ProvideAesGcmEncryptor()
	secretsRepository := core.ProvideEncryptedFileSecretRepository(osFileSystem, portsKeyring, aesGcmEncryptor)
	portsTemplater := templater.ProvideTextTemplater()
	fileSystemConfigRepository := core.ProvideFileSystemConfigRepository(osFileSystem, secretsRepository, portsTemplater)
	generateCommandHandler := handler.ProvideGenerateCommandHandler(fileSystemConfigRepository)
	return generateCommandHandler, nil
}

// wire.go:

var Adapter = wire.NewSet(scm.ProvideGitClient, scm.ProvideGit, wire.Bind(new(ports.Scm), new(*scm.Git)), container_image_repository.ProvideDockerRepository, wire.Bind(new(ports.ContainerImageRepository), new(*container_image_repository.DockerRepository)), container_orchestrator.ProvideKubernetes, wire.Bind(new(ports.ContainerOrchestrator), new(*container_orchestrator.Kubernetes)), filesystem.ProvideOsFileSystem, wire.Bind(new(ports.FileSystem), new(*filesystem.OsFileSystem)), keyring.ProvideZalandoKeyring, symmetric_encryptor.ProvideAesGcmEncryptor, wire.Bind(new(ports.SymmetricEncryptor), new(*symmetric_encryptor.AesGcmEncryptor)), templater.ProvideTextTemplater)

// CoreSet provides domain/core dependencies
var CoreSet = wire.NewSet(core.ProvideFileSystemConfigRepository, wire.Bind(new(core.ConfigRepository), new(*core.FileSystemConfigRepository)), core.ProvideDevProxyManager, core.ProvideEncryptedFileSecretRepository, core.ProvideEnvironmentEnsurer)

// CommandHandlerSet combines all sets needed for command handlers
var CommandHandlerSet = wire.NewSet(
	Adapter,
	CoreSet,
)
